### ISSUE TITLE
unable to open resource files

### ISSUE THREAD

**Issue by shiratorip** [YAUIO/osuSkinManager#1]
![image](https://github.com/user-attachments/assets/48918514-66c0-4061-9299-2629dd7dc527)
change 
`GUI::font.loadFromFile("deps/font.ttf");
    sf::Texture textIdle;
    sf::Texture textActive;
    textIdle.loadFromFile("deps/sfml.png");
    textActive.loadFromFile("deps/sfml.png");`
in main.cpp(21-25) to:
`std::filesystem::path deps_path = std::filesystem::current_path().parent_path() / "deps/";
GUI::font.loadFromFile(deps_path.string().append("font.ttf"));
sf::Texture textIdle;
sf::Texture textActive;
textIdle.loadFromFile(deps_path.string().append("sfml.png"));
textActive.loadFromFile(deps_path.string().append("sfml.png"));`

**Comment by YAUIO** [comment]
Fixed in [commit #0bca8b](https://github.com/YAUIO/osuSkinManager/commit/0bca8ba8a8e7cb1993be96980372195ea5aecd01)

**Comment by YAUIO** [comment]
want to add [that here](https://github.com/YAUIO/osuSkinManager/commit/1f5626aab5cc05249df03688a1ead37fe4e0c4b1)
